apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: k8s_namespace
  annotations:
    kubesphere.io/creator: admin
    servicemesh.kubesphere.io/enabled: "true"
  labels:
    app.kubernetes.io/compose: "true"
    app.kubernetes.io/name: k8s_namespace
    app.kubernetes.io/version: v1
spec:
  addOwnerRef: true
  componentKinds:
    - group: ""
      kind: Service
    - group: apps
      kind: Deployment
    - group: apps
      kind: StatefulSet
    - group: extensions
      kind: Ingress
    - group: servicemesh.kubesphere.io
      kind: Strategy
    - group: servicemesh.kubesphere.io
      kind: ServicePolicy
  selector:
    matchLabels:
      app.kubernetes.io/name: k8s_namespace
      app.kubernetes.io/version: v1
